### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by paranoya** [paranoya/population-synthesis-toolkit#45]
Right now, there are quite a few `print` statements here and there. We should definitely move to `logging`; the question is whether this is something for version 1 or version 2

**Comment by PabloCorcho** [comment]
VERSION 2

**Comment by PabloCorcho** [comment]
Besides, I don't think a logging facility is really necessary for this library...

**Comment by paranoya** [comment]
What to do with the `print` statements? Comment those at "INFO" level, and keep "WARNING"s?

**Comment by paranoya** [comment]
I actually find many of the "INFO"s useful (e.g. those that initialise the `SSP` classes). Maybe add a `verbose=True` parameter to all functions that currently `print` anything? I think this is the option I like the most...
