### ISSUE TITLE
Change filter names to SVO

### ISSUE THREAD

**Issue by Danieljl96** [paranoya/population-synthesis-toolkit#5]
Filters must have same name as used on SVO Filter Profile Service (GALEX/GALEX.FUV, SLOAN/SDSS.u,...)
Internally must be converted into local directory (Windows: GALEX\GALEX.FUV.dat, Linux: GALEX/GALEX.FUV.dat)
If filter is not stored, download it from the site (http://svo2.cab.inta-csic.es/theory/fps/getdata.php?format=ascii&id=SLOAN/SDSS.u)

**Comment by PabloCorcho** [comment]
I guess what you have in mind is to make use of https://astroquery.readthedocs.io/en/latest/svo_fps/svo_fps.html, right?

**Comment by paranoya** [comment]
Let's wait until the PR is merged...
