### ISSUE TITLE
Population Synthesis Tutorial

### ISSUE THREAD

**Issue by Danieljl96** [paranoya/population-synthesis-toolkit#6]
Create tutorials to illustrate population synthesis for a few models (DelayedTau, Exponential, Polynomial, TabularMFH,...):

1. Create model (`model1 = DelayedTau(tau=3*u.Gyr, ...)`)
2. Compute sed (`sed1 = model1.compute_SED(...)`)
3. Apply dust extinction
4. Compute photometry in selected filters

**Comment by PabloCorcho** [comment]
This has been addressed in multiple PRs
